import type { ArmorDef, CardDef, OffhandDef, WeaponDef } from "./types";

function card(partial: Partial<CardDef> & Pick<CardDef, "id" | "name" | "desc" | "icon">): CardDef {
  return {
    stamina: 1,
    reach: { min: 0, max: 0 },
    targetKind: "enemy",
    damage: 0,
    damageType: null,
    conditions: [],
    special: [],
    source: "weapon",
    ...partial,
  };
}

const UNIVERSAL: CardDef[] = [
  card({
    id: "step_close",
    name: "Step",
    desc: "Close distance to an enemy by 1.",
    icon: "👣",
    stamina: 0,
    reach: { min: 1, max: 99 },
    targetKind: "enemy",
    special: [{ type: "close_distance", amount: 1 }],
    source: "universal",
  }),
  card({
    id: "step_retreat",
    name: "Retreat",
    desc: "Push an enemy 1 further away.",
    icon: "↩️",
    stamina: 1,
    reach: { min: 0, max: 2 },
    targetKind: "enemy",
    special: [{ type: "push_enemy", amount: 1 }],
    source: "universal",
  }),
  card({
    id: "brace",
    name: "Brace",
    desc: "Gain 2 armor this turn.",
    icon: "🛡",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [{ type: "armor_this_turn", amount: 2 }],
    source: "universal",
  }),
  card({
    id: "hold_breath",
    name: "Hold Breath",
    desc: "End turn. Next turn, start with +3 stamina.",
    icon: "🌬️",
    stamina: 0,
    reach: "self",
    targetKind: "self",
    special: [{ type: "end_turn_draw_next_turn", bonusStamina: 3 }],
    source: "universal",
  }),
];

const ASHVERE_KNIFE_CARDS: CardDef[] = [
  card({
    id: "stab",
    name: "Stab",
    desc: "Basic melee. +2 damage vs enemies with a condition.",
    icon: "🗡️",
    stamina: 1,
    reach: { min: 0, max: 0 },
    damage: 4,
    damageType: "pierce",
  }),
  card({
    id: "stab",
    name: "Stab",
    desc: "Basic melee. +2 damage vs enemies with a condition.",
    icon: "🗡️",
    stamina: 1,
    reach: { min: 0, max: 0 },
    damage: 4,
    damageType: "pierce",
  }),
  card({
    id: "stab",
    name: "Stab",
    desc: "Basic melee. +2 damage vs enemies with a condition.",
    icon: "🗡️",
    stamina: 1,
    reach: { min: 0, max: 0 },
    damage: 4,
    damageType: "pierce",
  }),
  card({
    id: "sidestep",
    name: "Sidestep",
    desc: "Close 1 and stab for 3. Dodges next enemy melee.",
    icon: "💨",
    stamina: 1,
    reach: { min: 0, max: 1 },
    damage: 3,
    damageType: "pierce",
    special: [{ type: "close_distance", amount: 1 }, { type: "negate_hit" }],
  }),
  card({
    id: "backstab",
    name: "Backstab",
    desc: "Massive damage — target must be Helpless (stunned, unaware).",
    icon: "🔪",
    stamina: 2,
    reach: { min: 0, max: 0 },
    damage: 9,
    damageType: "pierce",
    special: [{ type: "requires_helpless" }],
  }),
  card({
    id: "envenom",
    name: "Envenom",
    desc: "Stab + apply Poisoned 3.",
    icon: "🐍",
    stamina: 1,
    reach: { min: 0, max: 0 },
    damage: 2,
    damageType: "pierce",
    conditions: [{ condition: "poisoned", stacks: 3, target: "enemy" }],
  }),
  card({
    id: "slip_through",
    name: "Slip Through",
    desc: "Push target back 1 and hide yourself.",
    icon: "🕳️",
    stamina: 2,
    reach: { min: 0, max: 1 },
    damage: 3,
    damageType: "pierce",
    special: [
      { type: "push_enemy", amount: 1 },
      { type: "hide_self", stacks: 1 },
    ],
  }),
];

const FOREMANS_PICK_CARDS: CardDef[] = [
  card({
    id: "swing",
    name: "Swing",
    desc: "Basic bludgeon.",
    icon: "⛏️",
    stamina: 1,
    damage: 5,
    damageType: "bludgeoning",
  }),
  card({
    id: "shatter",
    name: "Shatter",
    desc: "Heavy hit that strips enemy armor.",
    icon: "💥",
    stamina: 2,
    damage: 6,
    damageType: "bludgeoning",
  }),
  card({
    id: "heave",
    name: "Heave",
    desc: "Push target back 2.",
    icon: "🪨",
    stamina: 1,
    damage: 2,
    damageType: "bludgeoning",
    special: [{ type: "push_enemy", amount: 2 }],
  }),
  card({
    id: "crack_bone",
    name: "Crack Bone",
    desc: "Stun 1 turn.",
    icon: "🦴",
    stamina: 2,
    damage: 4,
    damageType: "bludgeoning",
    conditions: [{ condition: "stunned", stacks: 1, target: "enemy" }],
  }),
  card({
    id: "prospect",
    name: "Prospect",
    desc: "Draw 1 card and gain 1 Salt.",
    icon: "🔦",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [
      { type: "draw_cards", amount: 1 },
      { type: "gain_salt", amount: 1 },
    ],
  }),
];

const VIGIL_BLADE_CARDS: CardDef[] = [
  card({
    id: "slash",
    name: "Slash",
    desc: "Basic slash.",
    icon: "⚔️",
    stamina: 1,
    damage: 5,
    damageType: "slash",
  }),
  card({
    id: "riposte_stance",
    name: "Riposte Stance",
    desc: "Counter next melee attack for 5 slash.",
    icon: "🛡️",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [{ type: "riposte", damage: 5 }],
  }),
  card({
    id: "lunge",
    name: "Lunge",
    desc: "Close 1 and slash for 6.",
    icon: "🏃",
    stamina: 2,
    reach: { min: 0, max: 1 },
    damage: 6,
    damageType: "slash",
    special: [{ type: "close_distance", amount: 1 }],
  }),
  card({
    id: "disarm",
    name: "Disarm",
    desc: "Cancel target's next telegraph.",
    icon: "🚫",
    stamina: 2,
    reach: { min: 0, max: 1 },
    damage: 2,
    damageType: "slash",
    special: [{ type: "disarm_telegraph" }],
  }),
  card({
    id: "guard",
    name: "Guard",
    desc: "3 armor this turn.",
    icon: "🛡️",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [{ type: "armor_this_turn", amount: 3 }],
  }),
];

const CENSER_FLAIL_CARDS: CardDef[] = [
  card({
    id: "swing_censer",
    name: "Swing Censer",
    desc: "Holy bludgeon in melee.",
    icon: "⛓️",
    stamina: 1,
    reach: { min: 0, max: 1 },
    damage: 4,
    damageType: "holy",
  }),
  card({
    id: "censing_arc",
    name: "Censing Arc",
    desc: "Hit all enemies within distance 1. Apply Burning 2.",
    icon: "🌀",
    stamina: 2,
    reach: { min: 0, max: 1 },
    damage: 3,
    damageType: "holy",
    conditions: [{ condition: "burning", stacks: 2, target: "enemy" }],
    special: [{ type: "aoe_adjacent_distance" }],
  }),
  card({
    id: "sanctified_ground",
    name: "Sanctified Ground",
    desc: "Apply Burning 2 to all enemies at distance ≤1.",
    icon: "✨",
    stamina: 2,
    reach: "self",
    targetKind: "self",
    conditions: [{ condition: "burning", stacks: 2, target: "enemy" }],
    special: [{ type: "aoe_adjacent_distance" }],
  }),
  card({
    id: "incense_cloud",
    name: "Incense Cloud",
    desc: "Gain Hidden 1 + 2 armor this turn.",
    icon: "💨",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [
      { type: "hide_self", stacks: 1 },
      { type: "armor_this_turn", amount: 2 },
    ],
  }),
  card({
    id: "penitents_toll",
    name: "Penitent's Toll",
    desc: "Huge holy hit. Heals 4 if target is Burning.",
    icon: "🔔",
    stamina: 3,
    reach: { min: 0, max: 1 },
    damage: 8,
    damageType: "holy",
    special: [{ type: "heal", amount: 4 }],
  }),
];

const WARDENS_CROSSBOW_CARDS: CardDef[] = [
  card({
    id: "shoot",
    name: "Shoot",
    desc: "Ranged basic — requires distance ≥1.",
    icon: "🏹",
    stamina: 1,
    reach: { min: 1, max: 99 },
    damage: 4,
    damageType: "pierce",
  }),
  card({
    id: "piercing_shot",
    name: "Piercing Shot",
    desc: "Ignores armor. Distance ≥1.",
    icon: "⚡",
    stamina: 2,
    reach: { min: 1, max: 99 },
    damage: 6,
    damageType: "pierce",
  }),
  card({
    id: "pin_shot",
    name: "Pin Shot",
    desc: "Immobilize target 2 turns.",
    icon: "📍",
    stamina: 2,
    reach: { min: 1, max: 99 },
    damage: 3,
    damageType: "pierce",
    conditions: [{ condition: "immobilized", stacks: 2, target: "enemy" }],
  }),
  card({
    id: "overwatch",
    name: "Overwatch",
    desc: "Auto-shoot the first enemy to close within 1.",
    icon: "👁️",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [{ type: "overwatch", damage: 5, triggerBelowDistance: 2 }],
  }),
  card({
    id: "cull",
    name: "Cull",
    desc: "12 damage to a lowest-HP enemy. Costs 2 Salt.",
    icon: "💀",
    stamina: 3,
    reach: { min: 1, max: 99 },
    damage: 12,
    damageType: "pierce",
    special: [{ type: "salt_rite", saltCost: 2 }],
  }),
];

const ROUND_SHIELD_CARDS: CardDef[] = [
  card({
    id: "shield_bash",
    name: "Shield Bash",
    desc: "Bash + push 1.",
    icon: "🛡️",
    stamina: 1,
    damage: 2,
    damageType: "bludgeoning",
    special: [{ type: "push_enemy", amount: 1 }],
    source: "offhand",
  }),
  card({
    id: "shield_block",
    name: "Block",
    desc: "4 armor this turn.",
    icon: "🧱",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [{ type: "armor_this_turn", amount: 4 }],
    source: "offhand",
  }),
];

const MINERS_LANTERN_CARDS: CardDef[] = [
  card({
    id: "lantern_flare",
    name: "Flare",
    desc: "Draw 1 card.",
    icon: "🔥",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [{ type: "draw_cards", amount: 1 }],
    source: "offhand",
  }),
  card({
    id: "lantern_brand",
    name: "Brand",
    desc: "Apply Burning 2 to target.",
    icon: "🕯️",
    stamina: 1,
    reach: { min: 0, max: 1 },
    damage: 1,
    damageType: "fire",
    conditions: [{ condition: "burning", stacks: 2, target: "enemy" }],
    source: "offhand",
  }),
];

const LEATHER_ARMOR_CARDS: CardDef[] = [
  card({
    id: "vanish",
    name: "Vanish",
    desc: "Gain Hidden 2.",
    icon: "🌫️",
    stamina: 2,
    reach: "self",
    targetKind: "self",
    special: [{ type: "hide_self", stacks: 2 }],
    source: "armor",
  }),
];

const CHAINMAIL_CARDS: CardDef[] = [
  card({
    id: "set_feet",
    name: "Set Feet",
    desc: "Cleanse Immobilized / Slowed. 2 armor this turn.",
    icon: "🦶",
    stamina: 1,
    reach: "self",
    targetKind: "self",
    special: [{ type: "cleanse_conditions" }, { type: "armor_this_turn", amount: 2 }],
    source: "armor",
  }),
];

const SALT_RITE_CARDS: CardDef[] = [
  card({
    id: "rite_of_parting",
    name: "Rite of Parting",
    desc: "Consume a nearby corpse. Heal 4 and cleanse.",
    icon: "🕯️",
    stamina: 3,
    reach: "self",
    targetKind: "self",
    special: [
      { type: "salt_rite", saltCost: 1 },
      { type: "consume_corpse" },
      { type: "heal", amount: 4 },
      { type: "cleanse_conditions" },
    ],
    source: "salt_rite",
  }),
  card({
    id: "rite_of_long_night",
    name: "Rite of the Long Night",
    desc: "Cancel one telegraph on target.",
    icon: "🌙",
    stamina: 3,
    reach: { min: 0, max: 99 },
    damage: 0,
    targetKind: "enemy",
    special: [{ type: "salt_rite", saltCost: 2 }, { type: "disarm_telegraph" }],
    source: "salt_rite",
  }),
  card({
    id: "rite_of_last_light",
    name: "Rite of the Last Light",
    desc: "Full heal. Cleanse. Hide 3.",
    icon: "🌟",
    stamina: 3,
    reach: "self",
    targetKind: "self",
    special: [
      { type: "salt_rite", saltCost: 5 },
      { type: "heal", amount: 999 },
      { type: "cleanse_conditions" },
      { type: "hide_self", stacks: 3 },
    ],
    source: "salt_rite",
  }),
];

export const CARDS: readonly CardDef[] = [
  ...UNIVERSAL,
  ...ASHVERE_KNIFE_CARDS,
  ...FOREMANS_PICK_CARDS,
  ...VIGIL_BLADE_CARDS,
  ...CENSER_FLAIL_CARDS,
  ...WARDENS_CROSSBOW_CARDS,
  ...ROUND_SHIELD_CARDS,
  ...MINERS_LANTERN_CARDS,
  ...LEATHER_ARMOR_CARDS,
  ...CHAINMAIL_CARDS,
  ...SALT_RITE_CARDS,
];

export const CARD_MAP: ReadonlyMap<string, CardDef> = new Map(CARDS.map((c) => [c.id, c]));

export function getCard(id: string): CardDef | undefined {
  return CARD_MAP.get(id);
}

export const UNIVERSAL_CARD_IDS: readonly string[] = UNIVERSAL.map((c) => c.id);

export const WEAPONS: readonly WeaponDef[] = [
  {
    id: "ashvere_knife",
    name: "Ashvere Knife",
    subtitle: "Great-grandmother kept it sharp",
    icon: "🗡️",
    hand: "1h",
    primaryDamageType: "pierce",
    cardIds: ASHVERE_KNIFE_CARDS.map((c) => c.id),
  },
  {
    id: "foremans_pick",
    name: "Foreman's Pick",
    subtitle: "The name 'Ashvere' is scratched into the handle",
    icon: "⛏️",
    hand: "1h",
    primaryDamageType: "bludgeoning",
    cardIds: FOREMANS_PICK_CARDS.map((c) => c.id),
  },
  {
    id: "vigil_blade",
    name: "Vigil Blade",
    subtitle: "Standard issue. Every knight carried one.",
    icon: "⚔️",
    hand: "1h",
    primaryDamageType: "slash",
    cardIds: VIGIL_BLADE_CARDS.map((c) => c.id),
  },
  {
    id: "censer_flail",
    name: "Censer Flail",
    subtitle: "The thurible still smells of frankincense",
    icon: "⛓️",
    hand: "2h",
    primaryDamageType: "holy",
    cardIds: CENSER_FLAIL_CARDS.map((c) => c.id),
  },
  {
    id: "wardens_crossbow",
    name: "Warden's Crossbow",
    subtitle: "The order watched from a distance",
    icon: "🏹",
    hand: "2h",
    primaryDamageType: "pierce",
    cardIds: WARDENS_CROSSBOW_CARDS.map((c) => c.id),
  },
];

export const OFFHANDS: readonly OffhandDef[] = [
  {
    id: "round_shield",
    name: "Round Shield",
    icon: "🛡️",
    subtitle: "Reliable bulwark.",
    cardIds: ROUND_SHIELD_CARDS.map((c) => c.id),
    passiveBlockFirstHit: 2,
  },
  {
    id: "miners_lantern",
    name: "Miner's Lantern",
    icon: "🔦",
    subtitle: "Lit against the dark.",
    cardIds: MINERS_LANTERN_CARDS.map((c) => c.id),
  },
];

export const ARMORS: readonly ArmorDef[] = [
  {
    id: "leather_coat",
    name: "Leather Coat",
    icon: "🧥",
    subtitle: "Light and quick.",
    armor: 0,
    maxHpBonus: 0,
    maxStaminaModifier: 1,
    cardIds: LEATHER_ARMOR_CARDS.map((c) => c.id),
  },
  {
    id: "chainmail",
    name: "Chainmail",
    icon: "🔗",
    subtitle: "Linked steel.",
    armor: 2,
    maxHpBonus: 5,
    maxStaminaModifier: 0,
    cardIds: CHAINMAIL_CARDS.map((c) => c.id),
  },
];

export const WEAPON_MAP: ReadonlyMap<string, WeaponDef> = new Map(WEAPONS.map((w) => [w.id, w]));
export const OFFHAND_MAP: ReadonlyMap<string, OffhandDef> = new Map(OFFHANDS.map((o) => [o.id, o]));
export const ARMOR_MAP: ReadonlyMap<string, ArmorDef> = new Map(ARMORS.map((a) => [a.id, a]));
