import type { EnemyDef } from "./types";

function intent(
  abilityId: string,
  label: string,
  icon: string,
  kind: "attack" | "move_close" | "move_retreat" | "buff" | "summon" | "wait",
  resolveInTurns = 1,
): EnemyDef["intents"][number] {
  return { abilityId, label, icon, kind, resolveInTurns };
}

export const ENEMIES: readonly EnemyDef[] = [
  {
    id: "rat",
    name: "Ravager Rat",
    icon: "🐀",
    maxHp: 2,
    armor: 0,
    resistances: {},
    vulnerabilities: { fire: 1.5 },
    passives: [{ key: "swarm_bonus", value: 1 }],
    intents: [
      intent("rat_scurry", "Scurry", "👣", "move_close"),
      intent("rat_bite", "Bite", "🦷", "attack"),
    ],
    startDistance: 0,
    isBoss: false,
  },
  {
    id: "skeleton",
    name: "Skeleton",
    icon: "💀",
    maxHp: 14,
    armor: 1,
    resistances: { pierce: 0.5 },
    vulnerabilities: { bludgeoning: 1.5 },
    passives: [{ key: "reform_on_non_bludgeoning" }],
    intents: [
      intent("skeleton_advance", "Advance", "👣", "move_close"),
      intent("skeleton_slash", "Bone Slash", "🦴", "attack"),
      intent("skeleton_guard", "Shielded Stance", "🛡️", "buff"),
    ],
    startDistance: 0,
    isBoss: false,
  },
  {
    id: "zombie",
    name: "Rotting Zombie",
    icon: "🧟",
    maxHp: 8,
    armor: 0,
    resistances: {},
    vulnerabilities: { fire: 1.5, holy: 1.5 },
    passives: [],
    intents: [
      intent("zombie_shamble", "Shamble", "🚶", "move_close"),
      intent("zombie_grab", "Grab", "🫳", "attack"),
    ],
    startDistance: 1,
    isBoss: false,
  },
  {
    id: "ghost",
    name: "Mournful Ghost",
    icon: "👻",
    maxHp: 10,
    armor: 0,
    resistances: { slash: 0.5, pierce: 0.5 },
    vulnerabilities: { holy: 1.5 },
    passives: [{ key: "incorporeal" }],
    intents: [
      intent("ghost_chill", "Chill Touch", "❄️", "attack"),
      intent("ghost_phase", "Phase", "👻", "move_retreat"),
      intent("ghost_chill", "Chill Touch", "❄️", "attack"),
    ],
    startDistance: 1,
    isBoss: false,
  },
  {
    id: "vampire",
    name: "Blood Wraith",
    icon: "🧛",
    maxHp: 16,
    armor: 0,
    resistances: {},
    vulnerabilities: { holy: 1.5, fire: 1.5 },
    passives: [{ key: "lifesteal", value: 2 }],
    intents: [
      intent("vampire_stalk", "Stalk", "👁️", "move_retreat"),
      intent("vampire_drain", "Drain Bite", "🩸", "attack"),
    ],
    startDistance: 2,
    isBoss: false,
  },
  {
    id: "banshee",
    name: "Wailing Banshee",
    icon: "😱",
    maxHp: 10,
    armor: 0,
    resistances: { slash: 0.5, pierce: 0.5 },
    vulnerabilities: { holy: 1.5, bludgeoning: 1.5 },
    passives: [{ key: "incorporeal" }],
    intents: [
      intent("banshee_wail", "Wail", "😱", "attack"),
      intent("banshee_dirge", "Dirge", "🎵", "attack"),
    ],
    startDistance: 2,
    isBoss: false,
  },
  {
    id: "necromancer",
    name: "Necromancer",
    icon: "🧙",
    maxHp: 8,
    armor: 0,
    resistances: {},
    vulnerabilities: {},
    passives: [],
    intents: [
      intent("necro_bolt", "Dark Bolt", "🌑", "attack"),
      intent("necro_raise", "Raise Dead", "💀", "summon"),
    ],
    startDistance: 2,
    isBoss: false,
  },
  {
    id: "ghoul",
    name: "Lurking Ghoul",
    icon: "🧌",
    maxHp: 12,
    armor: 0,
    resistances: {},
    vulnerabilities: { holy: 1.5 },
    passives: [{ key: "feast_on_corpse" }, { key: "hidden_in_dark" }],
    intents: [
      intent("ghoul_pounce", "Pounce", "🐾", "attack"),
      intent("ghoul_slash", "Slash", "🗡️", "attack"),
    ],
    startDistance: 1,
    isBoss: false,
  },
  {
    id: "forsworn",
    name: "The Forsworn",
    icon: "⚔️",
    maxHp: 18,
    armor: 3,
    resistances: { slash: 0.5, pierce: 0.5 },
    vulnerabilities: { holy: 1.5, bludgeoning: 1.5 },
    passives: [{ key: "perjured_aura" }],
    intents: [
      intent("forsworn_cleave", "Cleave", "⚔️", "attack"),
      intent("forsworn_ward", "Ward Allies", "🔰", "buff"),
    ],
    startDistance: 0,
    isBoss: false,
  },
  {
    id: "gutborn_larva",
    name: "Gutborn Larva",
    icon: "🪱",
    maxHp: 1,
    armor: 0,
    resistances: {},
    vulnerabilities: { fire: 2 },
    passives: [],
    intents: [intent("larva_crawl", "Crawl", "🪱", "move_close")],
    startDistance: 1,
    isBoss: false,
  },

  {
    id: "boss_skeleton_lord",
    name: "Skeleton Lord",
    icon: "👑",
    maxHp: 32,
    armor: 3,
    resistances: { pierce: 0.5 },
    vulnerabilities: { bludgeoning: 1.5, holy: 1.25 },
    passives: [{ key: "phylactery_shield" }, { key: "shield_while_minions" }],
    intents: [
      intent("skeleton_slash", "Cleave", "🦴", "attack"),
      intent("skeleton_guard", "Bone Shield", "🛡️", "buff"),
      intent("skeleton_slash", "Cleave", "🦴", "attack"),
    ],
    startDistance: 0,
    isBoss: true,
  },
  {
    id: "boss_vampire_lord",
    name: "Vampire Lord",
    icon: "🧛",
    maxHp: 40,
    armor: 1,
    resistances: {},
    vulnerabilities: { holy: 1.5, fire: 1.5 },
    passives: [{ key: "lifesteal", value: 4 }],
    intents: [
      intent("vampire_stalk", "Stalk", "👁️", "move_retreat"),
      intent("vampire_drain", "Drain Bite", "🩸", "attack"),
      intent("vampire_drain", "Drain Bite", "🩸", "attack"),
    ],
    startDistance: 2,
    isBoss: true,
  },
  {
    id: "boss_lich",
    name: "The Lich King",
    icon: "☠️",
    maxHp: 50,
    armor: 2,
    resistances: {},
    vulnerabilities: { holy: 1.5, fire: 1.25 },
    passives: [{ key: "phylactery_shield" }],
    intents: [
      intent("lich_bolt", "Death Bolt", "🌑", "attack"),
      intent("lich_raise", "Mass Raise", "☠️", "summon"),
      intent("lich_nova", "Necrotic Nova", "💥", "attack"),
    ],
    startDistance: 2,
    isBoss: true,
  },
];

export const ENEMY_MAP: ReadonlyMap<string, EnemyDef> = new Map(ENEMIES.map((e) => [e.id, e]));

export function getEnemyDef(id: string): EnemyDef | undefined {
  return ENEMY_MAP.get(id);
}
